### ISSUE TITLE
相较于google wire的实现方式，go-spring通过反射实现依赖注入，性能损失大吗

### ISSUE THREAD

**Issue by CoderPoet** [didi/go-spring-doc#10]
google wire的依赖注入是在编译期就去分析依赖图谱，并自动生成注入依赖的代码，因此，运行时无性能消耗。

而go-spring是通过反射，在运行时注入依赖到结构体中，因此，不知golang的反射是否会成为性能瓶颈 （虽然貌似只有启动时注册bean到map里的时候会有较多消耗）？

因此，想知道二者的优劣，及作者选型时候的考虑

**Comment by lvan100** [comment]
我个人不喜欢通过代码生成的方式实现依赖注入，我认为那种方式很不灵便。
