### ISSUE TITLE
火钳 希望早日有GORM IRIS

### ISSUE THREAD

**Issue by lonerwolf** [didi/go-spring-doc#14]
火钳
另外本来想复制一份自己在代码上改的。。。但是那个包依赖好麻烦用replace都不行

**Comment by lvan100** [comment]
gorm 已经在做，快完成了。 iris 可以按照 spring-echo 的实现适配一下。期待你的 PR！

**Comment by lonerwolf** [comment]
> gorm 已经在做，快完成了。 iris 可以按照 spring-echo 的实现适配一下。期待你的 PR！

不好适配，本来想适配的，但是后来发现READ JSON木有 JWT CORS倒还可以写死写在初始化那里
